### ISSUE TITLE
Swift 3 support?

### ISSUE THREAD

**Issue by netgfx** [hemantasapkota/OpenSansSwift#2]
Can you support Swift 3.0 and make it available through Carthage as well?

Thanks!

**Comment by hemantasapkota** [comment]
Hi, 

Just added support for Swift 3. 

To install via. Carthage, add `github "hemantasapkota/OpenSansSwift" "swift3"` to your cart file and execute `carthage install`.

:)

**Comment by netgfx** [comment]
thanks!
